name: Update Instagram Feed

permissions:
  contents: write

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Debug write
        run: |
            echo "TEST $(date)" > index.html
            cat index.html

      - name: Commit & push index.html
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add index.html

          git diff --cached --quiet && echo "no changes" && exit 0

          git commit -m "update instagram feed"
          git push origin main
